"""add high risk reviews

Revision ID: 1644fb1c1451
Revises: d85ad25f66ec
Create Date: 2026-07-05 11:10:41.116191

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "1644fb1c1451"
down_revision: str | None = "d85ad25f66ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "high_risk_reviews",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("message_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "reviewed", "resolved", name="review_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("reviewed_by", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column("reviewed_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], name="fk_review_message"),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"], name="fk_review_reviewer"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_review_user"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_reviews_status", "high_risk_reviews", ["status", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_reviews_status", table_name="high_risk_reviews")
    op.drop_table("high_risk_reviews")
    # ### end Alembic commands ###
