"""add consultation records

Revision ID: a89e7df18324
Revises: fcecead92ecd
Create Date: 2026-07-05 10:54:50.855534

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "a89e7df18324"
down_revision: str | None = "fcecead92ecd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consultation_records",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("public_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("session_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("category_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("question_message_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("answer_message_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("citations", sa.JSON(), nullable=True),
        sa.Column("high_risk", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("disclaimer", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["answer_message_id"], ["messages.id"], name="fk_consultation_answer"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["legal_categories.id"], name="fk_consultation_category"
        ),
        sa.ForeignKeyConstraint(
            ["question_message_id"], ["messages.id"], name="fk_consultation_question"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], name="fk_consultation_session"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_consultation_user"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("answer_message_id", name="uk_consultation_answer"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        "idx_consultation_category_time",
        "consultation_records",
        ["category_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_consultation_user_time",
        "consultation_records",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("consultation_records")
    # ### end Alembic commands ###
