"""add knowledge materials

Revision ID: ceeb31ed5ac6
Revises: d12ac236028f
Create Date: 2026-07-05 11:20:52.225481

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "ceeb31ed5ac6"
down_revision: str | None = "d12ac236028f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_materials",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("public_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("category_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.Column("source_section", sa.String(length=255), nullable=True),
        sa.Column("file_hash", mysql.CHAR(length=64), nullable=False),
        sa.Column("file_key", sa.String(length=500), nullable=False),
        sa.Column("chunk_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            sa.Enum("indexing", "ready", "failed", name="material_status"),
            server_default="indexing",
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("uploaded_by", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["legal_categories.id"], name="fk_material_category"
        ),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], name="fk_material_uploader"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index("idx_material_hash", "knowledge_materials", ["file_hash"], unique=False)
    op.create_index("idx_material_status", "knowledge_materials", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_material_status", table_name="knowledge_materials")
    op.drop_index("idx_material_hash", table_name="knowledge_materials")
    op.drop_table("knowledge_materials")
    # ### end Alembic commands ###
