"""legal identity data layer

Revision ID: fcecead92ecd
Revises: 0001_initial_baseline
Create Date: 2026-07-05 10:23:30.994445

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'fcecead92ecd'
down_revision: str | None = '0001_initial_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('thread_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('workflow_version', sa.String(length=32), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', 'retrying', 'canceled', name='run_status'), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_summary', sa.String(length=500), nullable=True),
    sa.Column('started_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('finished_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_runs_status', 'agent_runs', ['status'], unique=False)
    op.create_index('idx_runs_thread', 'agent_runs', ['thread_id', 'started_at'], unique=False)
    op.create_table('legal_categories',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), server_default='user', nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', name='user_status'), server_default='active', nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('node_runs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('run_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('node_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', 'retrying', 'canceled', name='node_run_status'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('started_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('finished_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name='fk_node_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_node_runs_run', 'node_runs', ['run_id', 'started_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('category_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='session_status'), server_default='active', nullable=False),
    sa.Column('last_message_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['legal_categories.id'], name='fk_sessions_category'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_sessions_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_sessions_user_time', 'sessions', ['user_id', 'last_message_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('session_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role'), nullable=False),
    sa.Column('content', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('high_risk', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name='fk_messages_session', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_messages_session_time', 'messages', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('sessions')
    op.drop_table('node_runs')
    op.drop_table('users')
    op.drop_table('legal_categories')
    op.drop_index('idx_runs_thread', table_name='agent_runs')
    op.drop_index('idx_runs_status', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
